"""
Stratified Patient-Level Split Generator for Lung Tumor Segmentation.

Creates a reproducible patient-level split (44 Train, 9 Validation, 10 Test)
with approximate stratification by:
  - Tumor size category (Small < 1000 mm³, Medium 1000-5000 mm³, Large > 5000 mm³)
  - Tumor volume in mm³
  - Number of positive (tumor-containing) slices

The split ensures that each subset (Train, Val, Test) contains a representative
proportion of easy cases (large tumors) and hard cases (small tumors).

Usage:
    python -m src.preprocessing.create_split
"""

import os
import json
import numpy as np
import pandas as pd

from src.config import OUTPUT_DIR


# Tumor size category thresholds in mm³
SMALL_THRESHOLD = 1000.0    # Tumors below 1000 mm³ (~1 cm³)
MEDIUM_THRESHOLD = 5000.0   # Tumors between 1000-5000 mm³ (1-5 cm³)
                            # Tumors above 5000 mm³ are classified as Large

# Fixed seed for reproducibility across all runs
SPLIT_SEED = 42

# Target split sizes
N_TRAIN = 44
N_VAL = 9
N_TEST = 10


def classify_tumor_size(volume_mm3: float) -> str:
    """
    Assigns a tumor size category label based on the physical volume.
    
    Thresholds:
        Small:  < 1000 mm³  (sub-centimeter tumors, hardest to segment)
        Medium: 1000 - 5000 mm³  (moderate difficulty)
        Large:  > 5000 mm³  (easier to segment, larger surface area)
    
    Args:
        volume_mm3 (float): Tumor volume in cubic millimeters.
        
    Returns:
        str: One of "small", "medium", or "large".
    """
    if volume_mm3 < SMALL_THRESHOLD:
        return "small"
    elif volume_mm3 < MEDIUM_THRESHOLD:
        return "medium"
    else:
        return "large"


def create_stratified_split():
    """
    Creates and saves a reproducible patient-level split with approximate
    stratification by tumor size category.
    
    Algorithm:
        1. Read per-patient statistics from the EDA CSV (tumor volume, positive slices).
        2. Classify each patient into Small / Medium / Large tumor category.
        3. Within each category, sort patients by tumor volume for deterministic ordering.
        4. Distribute patients from each category across Train/Val/Test sets
           in approximate 70%/14%/16% proportions using round-robin allocation.
        5. Save the final split as a JSON file.
    
    Returns:
        dict: Split dictionary with keys "train", "val", "test", each containing
              a list of patient case_id strings.
    """
    # Path to the EDA statistics CSV generated by src/eda/eda_report.py
    eda_csv_path = os.path.join(OUTPUT_DIR, "eda_statistics.csv")
    
    if not os.path.exists(eda_csv_path):
        raise FileNotFoundError(
            f"EDA statistics file not found at: {eda_csv_path}\n"
            f"Please run 'python -m src.eda.eda_report' first to generate it."
        )
    
    # Load per-patient statistics from the EDA audit
    df = pd.read_csv(eda_csv_path)
    print(f"Loaded EDA statistics for {len(df)} patients from: {eda_csv_path}")
    
    # Verify we have exactly 63 patients
    assert len(df) == 63, f"Expected 63 patients but found {len(df)}"
    assert N_TRAIN + N_VAL + N_TEST == 63, "Split sizes must sum to 63"
    
    # Assign tumor size category to each patient based on physical volume
    df["tumor_category"] = df["tumor_volume_mm3"].apply(classify_tumor_size)
    
    # Print category distribution before splitting
    category_counts = df["tumor_category"].value_counts()
    print("\n--- Tumor Size Category Distribution (All 63 Patients) ---")
    for cat in ["small", "medium", "large"]:
        count = category_counts.get(cat, 0)
        print(f"  {cat.capitalize():8s}: {count} patients ({count / len(df) * 100:.1f}%)")
    
    # Set random seed for reproducibility
    rng = np.random.RandomState(SPLIT_SEED)
    
    # Separate patients into category groups, sorted by tumor volume within each group
    # Sorting ensures deterministic ordering before shuffling
    groups = {}
    for cat in ["small", "medium", "large"]:
        # Get patients belonging to this category, sorted by positive_slices and tumor_volume_mm3
        cat_df = df[df["tumor_category"] == cat].sort_values(["positive_slices", "tumor_volume_mm3"])
        cat_ids = cat_df["case_id"].tolist()
        # Shuffle within each category using the fixed random seed
        rng.shuffle(cat_ids)
        groups[cat] = cat_ids
    
    # Calculate how many patients from each category go to each split
    # Target proportions: Train ~70%, Val ~14%, Test ~16%
    train_ids = []
    val_ids = []
    test_ids = []
    
    for cat in ["small", "medium", "large"]:
        cat_ids = groups[cat]
        n_cat = len(cat_ids)
        
        # Calculate proportional allocation for this category
        # Using round() for approximate fair distribution
        n_test_cat = max(1, round(n_cat * N_TEST / 63))
        n_val_cat = max(1, round(n_cat * N_VAL / 63))
        n_train_cat = n_cat - n_test_cat - n_val_cat
        
        # Ensure at least 1 patient per category per split (when category has enough patients)
        if n_train_cat < 1 and n_cat >= 3:
            n_train_cat = 1
            remainder = n_cat - 1
            n_val_cat = min(n_val_cat, remainder // 2)
            n_test_cat = remainder - n_val_cat
        
        # Assign patients to splits
        test_ids.extend(cat_ids[:n_test_cat])
        val_ids.extend(cat_ids[n_test_cat:n_test_cat + n_val_cat])
        train_ids.extend(cat_ids[n_test_cat + n_val_cat:])
        
        print(f"\n  Category '{cat}' ({n_cat} patients): "
              f"Train={n_train_cat}, Val={n_val_cat}, Test={n_test_cat}")
    
    # Adjust if totals don't exactly match target sizes (due to rounding)
    # Move excess patients from train to val/test or vice versa
    _adjust_split_sizes(train_ids, val_ids, test_ids, rng)
    
    # Sort each split alphabetically for readability and determinism
    train_ids.sort()
    val_ids.sort()
    test_ids.sort()
    
    # Build the split dictionary
    split = {
        "train": train_ids,
        "val": val_ids,
        "test": test_ids,
        "metadata": {
            "seed": SPLIT_SEED,
            "n_train": len(train_ids),
            "n_val": len(val_ids),
            "n_test": len(test_ids),
            "small_threshold_mm3": SMALL_THRESHOLD,
            "medium_threshold_mm3": MEDIUM_THRESHOLD,
            "stratification_criteria": [
                "tumor_volume_mm3",
                "positive_slices",
                "tumor_category (small/medium/large)"
            ]
        }
    }
    
    # Save to JSON
    split_json_path = os.path.join(OUTPUT_DIR, "patient_split.json")
    with open(split_json_path, "w") as f:
        json.dump(split, f, indent=4)
    print(f"\nSaved patient split to: {split_json_path}")
    
    # Validate and print detailed summary
    _validate_and_print_summary(split, df)
    
    return split


def _adjust_split_sizes(train_ids: list, val_ids: list, test_ids: list,
                        rng: np.random.RandomState):
    """
    Adjusts split sizes to exactly match target counts (44/9/10) after
    proportional allocation may have introduced rounding errors.
    
    Moves patients between splits (preferring to move from/to train) until
    the exact target sizes are achieved.
    
    Args:
        train_ids: List of training patient IDs (modified in place).
        val_ids: List of validation patient IDs (modified in place).
        test_ids: List of test patient IDs (modified in place).
        rng: Random state for reproducible tie-breaking.
    """
    # While train set is too large, move patients to val or test
    while len(train_ids) > N_TRAIN:
        patient = train_ids.pop()
        if len(val_ids) < N_VAL:
            val_ids.append(patient)
        elif len(test_ids) < N_TEST:
            test_ids.append(patient)
        else:
            # Both val and test are at target, put back and break
            train_ids.append(patient)
            break
    
    # While train set is too small, pull patients from val or test
    while len(train_ids) < N_TRAIN:
        if len(val_ids) > N_VAL:
            patient = val_ids.pop()
            train_ids.append(patient)
        elif len(test_ids) > N_TEST:
            patient = test_ids.pop()
            train_ids.append(patient)
        else:
            break
    
    # Fine-tune val/test balance
    while len(val_ids) > N_VAL and len(test_ids) < N_TEST:
        test_ids.append(val_ids.pop())
    while len(test_ids) > N_TEST and len(val_ids) < N_VAL:
        val_ids.append(test_ids.pop())


def _validate_and_print_summary(split: dict, df: pd.DataFrame):
    """
    Validates the generated split for correctness and prints a detailed summary.
    
    Checks performed:
        1. No patient appears in more than one split (zero overlap).
        2. All 63 patients are accounted for (no patient left behind).
        3. Split sizes match targets (44/9/10).
        4. Prints per-split tumor statistics and category distribution.
    
    Args:
        split: The split dictionary containing train/val/test patient ID lists.
        df: The EDA statistics DataFrame with tumor volumes and categories.
    """
    train_set = set(split["train"])
    val_set = set(split["val"])
    test_set = set(split["test"])
    
    # Check 1: No overlap between any two splits
    assert len(train_set & val_set) == 0, "OVERLAP between Train and Val!"
    assert len(train_set & test_set) == 0, "OVERLAP between Train and Test!"
    assert len(val_set & test_set) == 0, "OVERLAP between Val and Test!"
    
    # Check 2: All 63 patients are accounted for
    all_ids = train_set | val_set | test_set
    all_eda_ids = set(df["case_id"].tolist())
    assert all_ids == all_eda_ids, f"Missing patients: {all_eda_ids - all_ids}"
    
    # Check 3: Correct split sizes
    assert len(split["train"]) == N_TRAIN, f"Train has {len(split['train'])}, expected {N_TRAIN}"
    assert len(split["val"]) == N_VAL, f"Val has {len(split['val'])}, expected {N_VAL}"
    assert len(split["test"]) == N_TEST, f"Test has {len(split['test'])}, expected {N_TEST}"
    
    print("\n" + "="*70)
    print("        STRATIFIED PATIENT SPLIT VALIDATION & SUMMARY")
    print("="*70)
    print(f"  [OK] Zero overlap between Train, Val, and Test sets")
    print(f"  [OK] All 63 patients accounted for")
    print(f"  [OK] Split sizes: Train={N_TRAIN}, Val={N_VAL}, Test={N_TEST}")
    
    # Per-split statistics
    for split_name, ids in [("Train", split["train"]),
                            ("Val", split["val"]),
                            ("Test", split["test"])]:
        subset = df[df["case_id"].isin(ids)]
        cat_counts = subset["tumor_category"].value_counts()
        
        print(f"\n  --- {split_name} Set ({len(ids)} patients) ---")
        print(f"    Tumor Volume (mm³): "
              f"min={subset['tumor_volume_mm3'].min():.1f}, "
              f"mean={subset['tumor_volume_mm3'].mean():.1f}, "
              f"median={subset['tumor_volume_mm3'].median():.1f}, "
              f"max={subset['tumor_volume_mm3'].max():.1f}")
        print(f"    Positive Slices:    "
              f"min={subset['positive_slices'].min()}, "
              f"mean={subset['positive_slices'].mean():.1f}, "
              f"max={subset['positive_slices'].max()}")
        print(f"    Total Slices:       {subset['num_slices'].sum()}")
        for cat in ["small", "medium", "large"]:
            count = cat_counts.get(cat, 0)
            print(f"    {cat.capitalize():8s} tumors: {count} "
                  f"({count / len(ids) * 100:.1f}%)")
    
    print("="*70)


def load_patient_split() -> dict:
    """
    Loads the saved patient split from disk.
    
    Returns:
        dict: Split dictionary with keys "train", "val", "test".
        
    Raises:
        FileNotFoundError: If patient_split.json does not exist.
    """
    split_json_path = os.path.join(OUTPUT_DIR, "patient_split.json")
    
    if not os.path.exists(split_json_path):
        raise FileNotFoundError(
            f"Patient split file not found at: {split_json_path}\n"
            f"Please run 'python -m src.preprocessing.create_split' first."
        )
    
    with open(split_json_path, "r") as f:
        split = json.load(f)
    
    print(f"Loaded patient split: Train={len(split['train'])}, "
          f"Val={len(split['val'])}, Test={len(split['test'])}")
    
    return split


if __name__ == "__main__":
    create_stratified_split()
